# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebenist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default=b'-', max_length=40, verbose_name='Titre')),
                ('prix', models.IntegerField(default=100, verbose_name='Prix')),
                ('description', models.TextField(blank=True, default=b'-', null=True, verbose_name='Description')),
                ('dispo', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fk_categ', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_categ', to='ebenist.Categorie', verbose_name='Categorie')),
            ],
            options={
                'db_table': 'creation',
                'verbose_name': 'creation',
                'verbose_name_plural': 'creations',
            },
        ),
        migrations.RemoveField(
            model_name='meuble',
            name='fk_categ',
        ),
        migrations.DeleteModel(
            name='Meuble',
        ),
    ]
