# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebenist', '0002_auto_20180615_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='date_fab',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date fabrication'),
        ),
    ]
